server:
  port: 18766
  tomcat:
    accesslog:
      enabled: true
    uri-encoding: utf-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/json,application/json
  context-path: /web


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:10.11.21.9}:${eureka.server.port:18761}/eureka/
  instance:
    prefer-ip-address: true
    health-check-url: /web/

info:
  component: mdm web


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

debug: true

spring:
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8


security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://10.11.21.9:9999/uaa/oauth/token
      userAuthorizationUri: http://10.11.21.9:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://10.11.21.9:9999/uaa/user
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
  basic:
    enabled: false

zuul:
  ignoredServices: "*"
  ignored-patterns: /app/**,/resources/**,/*.html,/*.ico
  routes:
    mdm:
      path: /mdm/**
      sensitiveHeaders: Cookie,Set-Cookie
    order:
      path: /order/**
      sensitiveHeaders: Cookie,Set-Cookie
#     stripPrefix: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.default.execution.timeout.enabled: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

#spring:
#  zipkin:
#    baseUrl: zipkin.einwin.com
#  sleuth:
#    sampler:
#      percentage: 1.0
#
#spring.rabbitmq:
#  host: mq.einwin.com
#  port: 5672
#  username: admin
#  password: admin

hystrix:
  threadpool:
    default:
      # Maximum number of concurrent requests when using thread pools (Default: 10)
      coreSize: 100
      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
      maxQueueSize: -1
      # Queue size rejection threshold (Default: 5)
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 20
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

#############ssoServer##############
localServerUrl: http://localhost:18766/
ssoServerUrl: http://10.11.21.9:9999/uaa/
